### ISSUE TITLE
cannot run successfully

### ISSUE THREAD

**Issue by morchius** [mrf345/django_gtts#1]
Hi, i pip installed but then the folder did not appear in main root of django project. Therefore I copied and pasted the gTTS folder so I have app available in my django project.
I followed all your instructions but I do not understand where to add the jinja template?!
Cheers

**Comment by mrf345** [comment]
Hello! You don't need to move it to your local project folder to work, it should work regardless of that. Just follow the `Setup` steps. Sorry for the `Jinja` confusing reference, I think in `Django` world they're called [Django Templates ](https://docs.djangoproject.com/en/2.2/topics/templates/). Good Luck!
